export { default as ArrowBottom } from "./arrow-bottom.png";
export { default as ArrowLeft } from "./arrow-left.png";
export { default as ArrowRight } from "./arrow-right.png";
export { default as CardImage } from "./card-img.png";
export { default as CardImage1 } from "./card-img1.png";
export { default as CardImage2 } from "./card-img2.png";
export { default as CarouselImg } from "./carousel-image.png";
export { default as CellImage } from "./cell-img.png";
export { default as CellPageCover } from "./cells-page-cover.png";
export { default as CertificadoCellCount } from "./certificado.png";
export { default as CertificadoAnalisis } from "./certificado-2.png";
export { default as ContactImg } from "./contact-img.png";
export { default as ContactImgMobile } from "./contact-img-mobile.png";
export { default as DescTecImgLeft } from "./desc-tec-img-left.png";
export { default as DescTecImgRight } from "./desc-tec-img-right.png";
export { default as DoctorImg } from "./doctor-img.png";
export { default as HomeScroll } from "./home-scroller.png";
export { default as LabImage } from "./lab-img.png";
export { default as LogoDark } from "./Logo_dark_short.png";
export { default as LogoWhite } from "./Logo_white_short.png";
export { default as CellIcon} from "./nav-cell-icon.png";
export { default as CloseIcon} from "./nav-close.png";
export { default as FAQIcon} from "./nav-faq-icon.png";
export { default as ISCT } from "./ISCT.png";
export { default as LabPageCover } from "./lab-page-cover.png";
export { default as LabIcon} from "./nav-lab-icon.png";
export { default as MenuIcon} from "./nav-menu.png";
export { default as OfferImgLeft } from "./offer-img-left.png";
export { default as OfferImgRight } from "./offer-img-right.png";
export { default as QuoraRedIcon } from "./quora_red.png";
export { default as PatIcon} from "./nav-pat-icon.png";
export { default as PressIcon} from "./nav-press-icon.png";
export { default as ValueImg1 } from "./value-img-1.png";
export { default as ValueImg2 } from "./value-img-2.png";
export { default as ValueImg3 } from "./value-img-3.png";
export { default as SaicelImgLeft } from "./saicel-img-left.png";
export { default as SaicelImgRight } from "./saicel-img-right.png";
export { default as SafeImgLeft } from "./safe-img-left.png";
export { default as SafeImgRight } from "./safe-img-right.png";
export { default as StudyImgLeft } from "./study-img-left.png";
export { default as StudyImgRight } from "./study-img-right.png";
